import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import CasaRosa from "../images/CasaRosa.jpg";
import Frasco from "../images/Frasco.jpg"
import Robot from "../images/Robot.jpg";
import CuartoRosa from "../images/CuartoRosa.jpg";
import CasaOscura from "../images/CasaOscura.jpg";
import Molino from "../images/Molino.jpg";
import Knowledge from "../images/Knowledge.png";
import Tiburoncin from "../images/Tiburoncin.png";
import Guitar from "../images/Guitar.jpg";
import Charro from "../images/Charro.jpg";
import Belico from "../images/Belico.jpg";
import Axolote from "../images/Axolote.jpg";
import PlantCig from "../images/PlantCigarrete.jpg";
import Uni from "../images/Uni.jpg"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Joshua Fuentes <a href="https://twitter.com/eluxorialmedal4">3D Designer</a>
        </h1>

        <section className={styles.description}>
          <p>I´m 3D desginer that loves create new things with Blender 💻</p>
        </section>

        <section className={styles.portafolio}>
         <h2 className={styles.subtitle}>💼 Portafolio 💼</h2>
          <p styles={styles.works}>Most recent works...</p>

          <div className={styles.box}>
              <div className={styles.boxImage}>
                <div>
                  <article>
                    <Image src={CasaRosa} className={styles.Image} alt="CasaRosa"/>
                  </article>
                </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Frasco} className={styles.Image} alt="Frasco"/>
                </article>
              </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Robot} className={styles.Image} alt="Robot"/>
                </article>
              </div>
            </div>
          </div>

          <div className={styles.box}>
            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={CuartoRosa} className={styles.Image} alt="CuartoRosa"/>
                </article>
              </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={CasaOscura} className={styles.Image} alt="CasaOscuro"/>
                </article>
              </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Tiburoncin} className={styles.Image} alt="Tiburoncin"/>
                </article>
              </div>
            </div>
          </div>

          <div className={styles.box}>
            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Charro} className={styles.Image} alt="Charro"/>
                </article>
              </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Axolote} className={styles.Image} alt="Ajolote"/>
                </article>
              </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Belico} className={styles.Image} alt="Charro Bélico"/>
                </article>
              </div>
            </div>
          </div>
          
          <div className={styles.box}>
            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={PlantCig} className={styles.Image} alt="Planta carnívora fumando"/>
                </article>
              </div>
            </div>

            <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Uni} className={styles.Image} alt="Logo de universidad en trajinera"/>
                </article>
              </div>
            </div>
          </div>

          <div className={styles.box}>
          <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Guitar} className={styles.Image} alt="Guitarra"/>
                </article>
              </div>
            </div>
          </div>

          <div className={styles.box}>
          <div className={styles.boxImage}>
              <div>
                <article>
                  <Image src={Molino} className={styles.Image} alt="Molino"/>
                </article>
              </div>
            </div>
          </div>
        </section>

        <section>
          <h2 className={styles.subtitle}>
            Knowledge
          </h2>

          <p className={styles.knowText}>
            Having knowledge in Blender and a little bit in Unity 🦖
          </p>
          <div className={styles.know}>
          <Image src={Knowledge} className={styles.knowImage} alt="Knowledge"/>
          </div>
        </section>

      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Loving game development 🎮
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  )
}
