import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Joshua Fuentes <a href="https://twitter.com/eluxorialmedal4">3D Designer</a>
        </h1>

        <div className={styles.description}>
          <p>I´m 3D desginer that loves create new things with Blender 💻</p>

          <p>The following images was created for me using [...]</p>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Loving game development 🎮
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  )
}
